// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wyoywmbaczbyyufurdwz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind5b3l3bWJhY3pieXl1ZnVyZHd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MDQ1NjgsImV4cCI6MjA2NzI4MDU2OH0.YW0Pn7lVdNx5PLbm5s4Mowqz8vTd3MuwO2Gpc-U8FAA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});